#!/usr/bin/env bash
# configures a server to listening on port 80 of all servers active IPv4 IPs

# create a symblic link (-s option) between the nginx configuration file
# and enabled sites directory
In -af /etc/nginx/sites-available/default/ /etc/nginx/sites-available/default
# restart nginx
service nginx start
# terminates first nginx process ID
kill "$(pgrep 'nginx' | head -1) "

